package com.hospital.citas;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.scheduling.annotation.EnableAsync;

@SpringBootApplication
@EnableAsync
public class CitasApplication {
	public static void main(String[] args) {
		SpringApplication.run(CitasApplication.class, args);
	}
}

/* PARA AGREGAR PAGINACIÓN

* IMPLEMENTAR LA PAGINACIÓN EN SP, REPOSITORY, SERVICE Y CONTROLLER
* IMPLEMENTAR API QUE CONSULTE CANTIDAD TOTAL DE REGISTROS
* AGREGAR HTML DE LA PAGINACIÓN
* AGREGAR VARIABLES PARA CONTROL DE PAGINACIÓN (CANTIDAD DE REGISTROS POR PÁGINA, CANTIDAD DE PÁGINAS, PÁGINA ACTUAL)
* CONSUMIR API DE CANTIDAD TOTAL DE REGISTROS
* IMPLEMENTAR PAGINADO EN CONSUMO DE API DE CONSULTA
* CREAR FUNCIONES PARA RENDERIZAR PAGINACIÓN
* CREAR FUNCIONES PARA AVANZAR Y RETROCEDER
* ACTUALIZAR CONTADORES SI PROCEDE*


AGREGAR UN BOTÓN PARA EXPORTAR, QUE SE MUESTRE SOLO CUANDO HAY REGISTROS
AGREGARLE UN EVENTO CLICK QUE AL PRESIONARLO INICIE EL PROCESO DE EXPORTACION
	SE ENVÍAN LOS FILTROS AL API DESDE EL FETCH

CREAR UN API QUE RECIBA LOS FILTROS
	CONFIGURA LOS HEADERS NECESARIOS
	LE PASA LOS FILTROS AL SERVICE

EL SERVICE TOMA LOS FILTROS Y VA A TRAR LA INFORMACIÓN
CUANDO TIENE LA INFORMACIÓN INICIA CON LA EXPORTACIÓN

LUEGO SE LE ENVÍA LA EXPORTACIÓN AL FRONTEND

EL FRONTEND TOMA LA INFORMACIÓN, CONSTRUYE EL ENLACE PARA DESCARGA Y ADJUNTA LA INFORMACIÓN AL ENLACE
SE INICIA LA DESCARGA A TRAVÉS DEL ENLACE
*/