-- 07:00:00 - 10:00:00 LA HORA DE INICIO ES MENOR Y LA HORA DE FIN YA ESTÁ CONTEMPLADA
-- 09:00:00 - 14:00:00 LA HORA DE INICIO YA ESTÁ CONTEMPLADA EN LA HORA DE INICIO, PERO LA HORA DE FIN NO

-- 1. BUSCA LOS REGISTRO QUE CONTEMPLEN TANTO LA HORA DE INICIO COMO FIN, PARA ESTO NO SE PROCESA PORQUE YA HAY UNO EXISTENTE QUE LO CUBRE
-- AMBOS DENTRO
SET @horaInicio = '10:00:00';
SET @horaFin = '11:30:00';
SELECT * 
FROM disponibilidadmedicos
WHERE IDMEDICO = 2 
AND idDiaSemana = 1 
and horaInicioAtencion <= @horaInicio and horaFinAtencion >= @horaFin;

-- 2. BUSCA LOS REGISTROS QUE SE ENCUENTRAN CONTEMPLADOS ENTRE LA HORA DE INICIO Y LA HORA DE FIN
-- AMBOS AFUERA
SET @horaInicio = '07:00:00';
SET @horaFin = '18:30:00';
SELECT * 
FROM disponibilidadmedicos
WHERE IDMEDICO = 2 AND idDiaSemana = 1 
and horaInicioAtencion > @horaInicio and horaFinAtencion < @horaFin;

-- 3. BUSCA EL REGISTRO MÁS CERCANO QUE DEBERÁ SER ACTUALIZADO CUANDO SE CUMPLA LO SIGUIENTE, LA HORA DE INICIO ESTÉ POR FUERA DEL REGISTRO, ES DECIR, SEA MENOR QUE LA HORA DE INICIO, EL REGISTRO QUE DEVUELVE SERÁ EL MÁS CERCANO 
-- INICIO AFUERA
SET @horaInicio = '07:00:00';
SELECT * 
FROM disponibilidadmedicos
WHERE IDMEDICO = 2 AND idDiaSemana = 1 
and horaInicioAtencion > @horaInicio
ORDER BY horaInicioAtencion ASC
LIMIT 1;

-- 4. BUSCA EL REGISTRO MÁS CERCANO QUE DEBERÁ SER ACTUALIZADO CUANDO SE CUMPLA LO SIGUIENTE, LA HORA DE FIN ESTÉ POR FUERA DEL REGISTRO, ES DECIR, SEA MAYOR QUE LA HORA DE FIN, EL REGISTRO QUE DEVUELVE SERÁ EL MÁS CERCANO 
-- FIN AFUERA
SET @horaFin = '18:30:00';
SELECT * 
FROM disponibilidadmedicos
WHERE IDMEDICO = 2 AND idDiaSemana = 1 
and horaFinAtencion < @horaFin
ORDER BY horaFinAtencion DESC
LIMIT 1;
